### ISSUE TITLE
Medium shows up as Satire/Fake News

### ISSUE THREAD

**Issue by JeffreyATW** [JeffreyATW/mbfc_icon#1]
Thanks to [SportsPickle](https://medium.com/sportspickle). Implement better matching by URL rather than subdomain.

**Comment by JohnnyWalkerDigital** [comment]
Seems to be fixed?

**Comment by JeffreyATW** [comment]
No, it was changed on the MBFC side. Working on a URL matching fix now.

**Comment by JeffreyATW** [comment]
Closed by 6df17fc.
