### ISSUE TITLE
Alerts absent from Children's Health Defense pages; other possible issues

### ISSUE THREAD

**Issue by grahamperrin** [JeffreyATW/mbfc_icon#10]
### Symptom A

Whilst https://mediabiasfactcheck.com/childrens-health-defense/ warns of quackery and **Conspiracy-Pseudoscience**: 

* the yellow **CP** icon is absent from pages such as https://childrenshealthdefense.org/news/plague-of-corruption-book-the-talented-dr-judy-mikovits/

Please see https://github.com/RatNeurons/fact-layer/issues/2

**Comment by grahamperrin** [comment]
### Symptom B

Whilst https://mediabiasfactcheck.com/daily-beast/ reports _**MOSTLY FACTUAL**_: 

* the extension reports _Factual reporting: **HIGH**_ at https://www.thedailybeast.com/stella-immanuel-trumps-new-covid-doctor-believes-in-alien-dna-demon-sperm-and-hydroxychloroquine

![image](https://user-images.githubusercontent.com/192271/88770586-f92bd680-d175-11ea-9d49-c129003acdf0.png)

Lazy guess: a fix for Symptom A will also fix Symptom B …

**Comment by JeffreyATW** [comment]
My icon extension has been superseded by [this one](https://chrome.google.com/webstore/detail/official-media-biasfact-c/ganicjnkcddicfioohdaegodjodcbkkh?hl=en-US).
