### ISSUE TITLE
not affiliated ≠ Official

### ISSUE THREAD

**Issue by grahamperrin** [JeffreyATW/mbfc_icon#5]
I'd love to recommend this extension to staff and students at work, but I hesitate before describing it as _Official_. https://addons.mozilla.org/addon/media-bias-fact-check-icon/ offers the contradiction: 

> … Not affiliated with MBFC …

Please, might you change the name? 

From: 

- _Official Media Bias Fact Check Icon_ 

to: 

- _Media Bias Fact Check icon_

TIA

----

Note, this is **not** to doubt the goodness of the extension. Just attention to detail with naming (I should expect some academic colleagues to similarly question the 'official' wording).

**Comment by JeffreyATW** [comment]
Dave Van Zandt, the owner of MBFC, asked me to call the exension “official”. You can email him if you’d like verification.

**Comment by grahamperrin** [comment]
@JeffreyATW thanks, the clarification is enough, I'll trust you. Thanks for the openness :+1:
