### ISSUE TITLE
No icon at The Guardian

### ISSUE THREAD

**Issue by grahamperrin** [JeffreyATW/mbfc_icon#6]
Hi

https://mediabiasfactcheck.com/the-guardian/ recognises The Guardian. 

The extension does not. Third screenshot below, <https://www.theguardian.com/education/2018/jul/26/rise-in-unconditional-offers-prompts-call-for-university-admissions-overhaul>: 

![2018-11-03 09 31 59 education in the media thursday 26 july 2018 - education in the media - mozilla firefox](https://user-images.githubusercontent.com/192271/47950615-8e238080-df4c-11e8-9218-751e15f360b3.png)

![2018-11-03 09 35 39 browsers](https://user-images.githubusercontent.com/192271/47950619-924f9e00-df4c-11e8-8aa0-76545e8da041.png)

![2018-11-03 09 36 46 rise in unconditional offers prompts call for university admissions overhaul education the guardian - mozilla firefox](https://user-images.githubusercontent.com/192271/47950622-98de1580-df4c-11e8-9a4d-28719354e9f7.png)

![2018-11-03 09 37 11 the most disgusting student flat in britain in sheffield university s endcliffe village daily mail online - mozilla firefox](https://user-images.githubusercontent.com/192271/47950626-9f6c8d00-df4c-11e8-83e8-848382692541.png)

![2018-11-03 09 37 27 university tuition fees could be slashed from 9 000 to 6 500 under plans to reform system which could cost 3billion - mozilla firefox](https://user-images.githubusercontent.com/192271/47950628-a4314100-df4c-11e8-833f-b373adf18ad2.png)

Reproducible at (UK) home page <https://www.theguardian.com/uk>.

**Comment by JeffreyATW** [comment]
This is likely because the source listed on the MBFC page has a `/us` in the path. As a rule, I don't add a bias to the root domain if there is a path specified - for example, if someone was publishing something at medium.com or wordpress.com, I wouldn't give the entire domain a bias.

The proper solution is to ask the MBFC folks to change their source path to `/`, but it might be intentional on their part to only categorize the US section.

**Comment by grahamperrin** [comment]
Thanks, I have written to the e-mail address given at https://mediabiasfactcheck.com/about/

**Comment by grahamperrin** [comment]
Unless I'm missing something, no response :-(

**Comment by grahamperrin** [comment]
Cross reference https://twitter.com/grahamperrin/status/1183304519691751424

**Comment by grahamperrin** [comment]
https://www.theguardian.com/uk/commentisfree for example: 

- was not recognised a few weeks ago
- is now recognisably left-centre, with reference to https://mediabiasfactcheck.com/the-guardian/

:+1:
